version: '3.8'

services:

  app:
    build: ./app
    container_name: app
    restart: always
    environment:
      - APP_NAME=acc2
    expose:
      - 8080

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - 80:80